---
- name: "Copy dist to EC2 server"
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: "Install dependencies"
  become: true
  apt:
    name: ["nodejs", "npm", "python3", "tar", "gzip"]
    state: latest
    update_cache: yes

- name: "Create directory for backend"
  file:
    path: /home/ubuntu/backend/
    state: directory

- name: unzip
  become: true
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .

- name: start server
  become: true
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop default
    pm2 start npm --name backend -- start
# - name: "Extract artifact to home"
#   # become: yes
#   unarchive:
#     src: ~/project/artifact.tar.gz
#     dest: /home/ubuntu
#     copy: no

# - name: "Install packages"
#   npm:
#     path: /home/ubuntu

# - name: "Run npm"
#   # become: yes
#   shell: |
#     pm2 stop default
#     pm2 start npm -- start